### ISSUE TITLE
How to override ports and debug mode (config)

### ISSUE THREAD

**Issue by MichelDiz** [calummoore/dgraph-node#2]
The Dgraph defaults is 8080. The client is set to 9080. Some people tend to change the port in cases of port conflict. It would be nice to have described a default setting that is changeable over time.

PS: `let client = new DgraphClient('localhost:8080');`

Cheers

**Comment by MichelDiz** [comment]
I realized that the PORT is for gRPC. Forgot about it. However, how to set debug mode?

**Comment by calummoore** [comment]
I've updated the README.md so it should now be clear.
