### ISSUE TITLE
TypeError: DgraphClient is not a constructor

### ISSUE THREAD

**Issue by pmualaba** [calummoore/dgraph-node#4]
Hi, 

I use the following code (from github readme) to initialize a DgraphClient:

const grpc = require('grpc')
const DgraphClient = require('dgraph-node')
const db = new DgraphClient({
    url: 'localhost:9080',
    debug: false,
    credentials: grpc.credentials.createInsecure()
})

But when I try to instantiate a DgraphClient i get following error:
I use node.js version 8.6.0

TypeError: DgraphClient is not a constructor
17:08:51 0|server   |     at Object.<anonymous> (.../nodejs/server.js:16:12)
17:08:51 0|server   |     at Module._compile (module.js:624:30)
17:08:51 0|server   |     at Object.Module._extensions..js (module.js:635:10)
17:08:51 0|server   |     at Module.load (module.js:545:32)
17:08:51 0|server   |     at tryModuleLoad (module.js:508:12)
17:08:51 0|server   |     at Function.Module._load (module.js:500:3)
17:08:51 0|server   |     at /usr/lib/node_modules/pm2/lib/ProcessContainer.js:328:23
17:08:51 0|server   |     at /usr/lib/node_modules/pm2/node_modules/async/dist/async.js:421:16
17:08:51 0|server   |     at next (/usr/lib/node_modules/pm2/node_modules/async/dist/async.js:5302:29)
17:08:51 0|server   |     at /usr/lib/node_modules/pm2/node_modules/async/dist/async.js:906:16
2017-11-26 17:08:51: App name:server id:0 disconnected

**Comment by pmualaba** [comment]
OK, seems like you have to require it using the following syntax:

const DgraphClient = require('dgraph-node').default

**Comment by calummoore** [comment]
Yes, ES6 import statements enforce this. I'll add it to the readme.md though for future reference.
