### ISSUE TITLE
I've got errors with gRPC

### ISSUE THREAD

**Issue by MichelDiz** [calummoore/dgraph-node#6]
I did some testing. I am using the recent version of Dgraph Dev. I deleted all Dgraph (mean from scratch) files, created other tests with Dgraph Node from scratch. And not one of them connects with the Dgraph. Despite being able to query the db by the UI.

One of my tests returned this error below (I used some starter Kit). The others remained silent.

I'm debugging everywhere. (eg. dgraph server --memory_mb 2048 --zero localhost:5080 --ui assets --debugmode)

```cmd
error { Error: unknown service protos.Dgraph
    at C:\Users\MichelDiz\Desktop\TestecomDgraph\node_modules\grpc\src\client.js:554:15 code: 12, metadata: Metadata { _internal_repr: {} } }
```

**Comment by MichelDiz** [comment]
I downgraded to version 9.1 - So maybe this was on account of incompatible proto. 

`(node:72676) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: unknown service protos.Dgraph`

**Comment by wildermuthn** [comment]
Can confirm that 0.1.8 doesn't work with dgraph 9.4. The Java client has the same issue: https://github.com/dgraph-io/dgraph4j/issues/38

**Comment by wildermuthn** [comment]
Looks to be the culprit: 

https://github.com/calummoore/dgraph-node/blob/47831596912ab10264fbc44139bcdace635ef51e/update-protos.sh#L9-L13

**Comment by MichelDiz** [comment]
I had noticed, tried to update myself. But Dgraph was updated and separated the Protos in two.
And theres no https://raw.githubusercontent.com/dgraph-io/dgraph/v0.9.4/protos/xxxxxx
> Proto definitions are split into intern and api. Users using v0.9.x of the Go client will have to change their code to use api instead of proto as package name.

**Comment by gpahal** [comment]
It works if you use [https://raw.githubusercontent.com/dgraph-io/dgraph/v0.9.4/protos/api.proto](https://raw.githubusercontent.com/dgraph-io/dgraph/v0.9.4/protos/api.proto) and change protos.js accordingly.

**Comment by calummoore** [comment]
This is now fixed for the latest version on NPM - dgraph-node@0.1.9

**Comment by MichelDiz** [comment]
Tested and confirmed. Thank you Calum Moore!
